# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "922b6f58f8ab79e83362e840cb4503b4"
name = "walletx-1"
application_url = "https://shopify-walletx-1.onrender.com/"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://shopify-walletx-1.onrender.com/auth/callback" ]
